In [155]:
## function to fetching data on wiki
def looker():
    '''
    This function gets no arguments. It asks for a topic of your interest.
    It saves the information you seek into a global object dataframe in case you want to use it.
    then to a csv file, but you need to change directory of your choice first.
    The function keeps on asking you for you are looking for, If you wish to stop the extraction, write: terminate'''
    import json
    import wptools
    import wikipedia
    import pandas as pd
    global file
    while True:
        topic = input('Write What you looking for: \nOR Write "terminate" to stop extracting')
        if topic == 'terminate':
            break
        #n = int(input('Number of articles you want to extract ?'))
        category = str(input('Write the category: '))
        articles = wikipedia.search(str(topic),results=1)
        file = []
        global df
        for article in articles:
            try: 
                #page = wptools.page(article) # querying information from each item using wptools 
                #page.get_query() #Fetch information from Mediawiki:Query API
                #page.get_parse() #OR fetch info from Mediawiki:Parse API
                #page.get() # necessary to extract or the next lines will come up with nothing
                #wikipedia_title = page.data['title'] # extract title of every page
                wikipedia_precontent = wikipedia.page(article) # fetching for the page using wikipedia.page 
                wikipedia_content = wikipedia_precontent.content #fetching page content
                file.append({'category': category, # appending to a list then converting it to a dict
                                      'content': wikipedia_content}) # type so that it is convertable to pandas DataFrame
                

            except: # Error handling when : the topic ID has some error and can only fetched independently 
                print(f"""This Topic: '{article}' needs to be searched independently""")
        
        df = pd.DataFrame(file)
        df.to_csv(f'E:\\Sports\\{topic}.csv') # saving the dataframe into a csv file format
        #print(df)

In [ ]:
looker()

In [147]:
import glob
import pandas as pd

# Set the directory path where the CSV files are stored
directory_path = 'E:\\Sports\\Archers'

# Get a list of all CSV files in the directory
csv_files = glob.glob(directory_path + '/*.csv')

# Loop through each CSV file and read it into a DataFrame
data_frames = []
for file in csv_files:
    df = pd.read_csv(file)
    data_frames.append(df)

# Concatenate all DataFrames into a single DataFrame
merged_df = pd.concat(data_frames,ignore_index=True)

# Display the merged DataFrame
print(merged_df)

   Unnamed: 0         category  \
0           0         Baseball
1           0          Archers
2           0       Cricketers
3           0       Kickboxers
4           0       Cricketers
..        ...              ...
94          0       Basketball
95          0       Cricketers
96          0       Cricketers
97          0         Baseball
98          0  Marathon Runner

                                              content
0   Aaron James Judge (born April 26, 1992) is an ...
1   Aída Nabila Román Arroyo (born May 21, 1988) i...
2   Sir Andrew John Strauss  (born 2 March 1977) i...
3   Andreas "Andy" Hug (7 September 1964 – 24 Augu...
4   Anil Kumble (pronunciation ; born 17 October 1...
..                                                ...
94  Timothy Theodore Duncan (born April 25, 1976) ...
95  Wasim Akram HI (Urdu: وسیم اکرم; born 3 June 1...
96  Wasim Bari (Urdu: وسیم باری; born 23 March 194...
97  Willie Howard Mays Jr. (born May 6, 1931), nic...
98  Wilson Kipsang Kiprotich (born 15 March 1982) ...

[99 rows x 3 columns]

In [157]:
#the newly concatenated information has index problem that is why we need to only catch columns we need into a new df
df_new = pd.DataFrame()
df_new['category'] = merged_df['category']
df_new['content'] = merged_df['content']

In [158]:
df_new

           category                                            content
0          Baseball  Aaron James Judge (born April 26, 1992) is an ...
1           Archers  Aída Nabila Román Arroyo (born May 21, 1988) i...
2        Cricketers  Sir Andrew John Strauss  (born 2 March 1977) i...
3        Kickboxers  Andreas "Andy" Hug (7 September 1964 – 24 Augu...
4        Cricketers  Anil Kumble (pronunciation ; born 17 October 1...
..              ...                                                ...
94       Basketball  Timothy Theodore Duncan (born April 25, 1976) ...
95       Cricketers  Wasim Akram HI (Urdu: وسیم اکرم; born 3 June 1...
96       Cricketers  Wasim Bari (Urdu: وسیم باری; born 23 March 194...
97         Baseball  Willie Howard Mays Jr. (born May 6, 1931), nic...
98  Marathon Runner  Wilson Kipsang Kiprotich (born 15 March 1982) ...

[99 rows x 2 columns]

In [159]:
# index = False to avoid random needless column addition
df_new.to_csv('E:\\Sports_Data.csv',index=False)

In [160]:
pd.read_csv('E:\\Sports_Data.csv')

           category                                            content
0          Baseball  Aaron James Judge (born April 26, 1992) is an ...
1           Archers  Aída Nabila Román Arroyo (born May 21, 1988) i...
2        Cricketers  Sir Andrew John Strauss  (born 2 March 1977) i...
3        Kickboxers  Andreas "Andy" Hug (7 September 1964 – 24 Augu...
4        Cricketers  Anil Kumble (pronunciation ; born 17 October 1...
..              ...                                                ...
94       Basketball  Timothy Theodore Duncan (born April 25, 1976) ...
95       Cricketers  Wasim Akram HI (Urdu: وسیم اکرم; born 3 June 1...
96       Cricketers  Wasim Bari (Urdu: وسیم باری; born 23 March 194...
97         Baseball  Willie Howard Mays Jr. (born May 6, 1931), nic...
98  Marathon Runner  Wilson Kipsang Kiprotich (born 15 March 1982) ...

[99 rows x 2 columns]